version: '3'

services:
  paper-summarizer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped